COMMAND_PREFIX = "/"

PRESETS = {
    "sunset": {
        "background": "#FF4500",
        "text_default": "#FFDAB9",
        "text_user_cmd": "#FF6347",
        "text_info": "#FFA07A",
        "text_error": "#8B0000",
        "font": ("Consolas", 20),
        "button_bg": "#FF7F50",
        "button_fg": "#FFF5EE",
        "button_hover_bg": "#FF6347",
        "button_active_bg": "#CD5C5C",
        "entry_font": ("Consolas", 28),
    },
    "mint": {
        "background": "#98FF98",
        "text_default": "#004d40",
        "text_user_cmd": "#00695c",
        "text_info": "#00796b",
        "text_error": "#b71c1c",
        "font": ("Consolas", 20),
        "button_bg": "#66bb6a",
        "button_fg": "#004d40",
        "button_hover_bg": "#388e3c",
        "button_active_bg": "#2e7d32",
        "entry_font": ("Consolas", 28),
    },
    "lavender": {
        "background": "#E6E6FA",
        "text_default": "#6A5ACD",
        "text_user_cmd": "#7B68EE",
        "text_info": "#9370DB",
        "text_error": "#8B0000",
        "font": ("Consolas", 20),
        "button_bg": "#7B68EE",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#6A5ACD",
        "button_active_bg": "#483D8B",
        "entry_font": ("Consolas", 28),
    },
    "midnight": {
        "background": "#191970",
        "text_default": "#F8F8FF",
        "text_user_cmd": "#00BFFF",
        "text_info": "#1E90FF",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#000080",
        "button_fg": "#F8F8FF",
        "button_hover_bg": "#4169E1",
        "button_active_bg": "#00008B",
        "entry_font": ("Consolas", 28),
    },
    "peach": {
        "background": "#FFE5B4",
        "text_default": "#D2691E",
        "text_user_cmd": "#FF7F50",
        "text_info": "#FF6347",
        "text_error": "#B22222",
        "font": ("Consolas", 20),
        "button_bg": "#FF8C00",
        "button_fg": "#D2691E",
        "button_hover_bg": "#FF7F50",
        "button_active_bg": "#CD5C5C",
        "entry_font": ("Consolas", 28),
    },
    "slate": {
        "background": "#708090",
        "text_default": "#F5F5F5",
        "text_user_cmd": "#778899",
        "text_info": "#B0C4DE",
        "text_error": "#DC143C",
        "font": ("Consolas", 20),
        "button_bg": "#2F4F4F",
        "button_fg": "#F5F5F5",
        "button_hover_bg": "#4682B4",
        "button_active_bg": "#5F9EA0",
        "entry_font": ("Consolas", 28),
    },
    "tropical": {
        "background": "#FFFAF0",
        "text_default": "#228B22",
        "text_user_cmd": "#32CD32",
        "text_info": "#3CB371",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#20B2AA",
        "button_fg": "#228B22",
        "button_hover_bg": "#2E8B57",
        "button_active_bg": "#006400",
        "entry_font": ("Consolas", 28),
    },
    "green": {
        "background": "#000000",
        "text_default": "#00FF00",
        "text_user_cmd": "#00FF00",
        "text_info": "#00FFFF",
        "text_error": "#FF0000",
        "font": ("Consolas", 20),
        "button_bg": "#003300",
        "button_fg": "#00FF00",
        "button_hover_bg": "#005500",
        "button_active_bg": "#007700",
        "entry_font": ("Consolas", 28),
    },
    "blue": {
        "background": "#001f3f",
        "text_default": "#7FDBFF",
        "text_user_cmd": "#0074D9",
        "text_info": "#39CCCC",
        "text_error": "#FF4136",
        "font": ("Consolas", 20),
        "button_bg": "#004080",
        "button_fg": "#7FDBFF",
        "button_hover_bg": "#0074D9",
        "button_active_bg": "#0059b3",
        "entry_font": ("Consolas", 28),
    },
    "red": {
        "background": "#2B0000",
        "text_default": "#FF4136",
        "text_user_cmd": "#FF851B",
        "text_info": "#FFDC00",
        "text_error": "#FF0000",
        "font": ("Consolas", 20),
        "button_bg": "#660000",
        "button_fg": "#FF4136",
        "button_hover_bg": "#990000",
        "button_active_bg": "#cc0000",
        "entry_font": ("Consolas", 28),
    },
    "purple": {
        "background": "#1a001a",
        "text_default": "#DA70D6",
        "text_user_cmd": "#BA55D3",
        "text_info": "#D8BFD8",
        "text_error": "#FF1493",
        "font": ("Consolas", 20),
        "button_bg": "#4B0082",
        "button_fg": "#DA70D6",
        "button_hover_bg": "#6A0DAD",
        "button_active_bg": "#800080",
        "entry_font": ("Consolas", 28),
    },
    "gray": {
        "background": "#1C1C1C",
        "text_default": "#C0C0C0",
        "text_user_cmd": "#A9A9A9",
        "text_info": "#D3D3D3",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#333333",
        "button_fg": "#C0C0C0",
        "button_hover_bg": "#505050",
        "button_active_bg": "#696969",
        "entry_font": ("Consolas", 28),
    },
    "orange": {
        "background": "#332200",
        "text_default": "#FFA500",
        "text_user_cmd": "#FF8C00",
        "text_info": "#FFD700",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#804000",
        "button_fg": "#FFA500",
        "button_hover_bg": "#cc6600",
        "button_active_bg": "#FF8C00",
        "entry_font": ("Consolas", 28),
    },
    "red_cherry": {
        "background": "#1a0005",
        "text_default": "#FF4C4C",
        "text_user_cmd": "#FF1A40",
        "text_info": "#FFB6C1",
        "text_error": "#FF0033",
        "font": ("Consolas", 20),
        "button_bg": "#660022",
        "button_fg": "#FF4C4C",
        "button_hover_bg": "#990033",
        "button_active_bg": "#cc0033",
        "entry_font": ("Consolas", 28),
    },
    "aqua": {
        "background": "#002f2f",
        "text_default": "#00FFFF",
        "text_user_cmd": "#20B2AA",
        "text_info": "#7FFFD4",
        "text_error": "#FF6347",
        "font": ("Consolas", 20),
        "button_bg": "#004d4d",
        "button_fg": "#00FFFF",
        "button_hover_bg": "#008080",
        "button_active_bg": "#00CED1",
        "entry_font": ("Consolas", 28),
    },
    "cyberpunk": {
        "background": "#0a0a0a",
        "text_default": "#39FF14",
        "text_user_cmd": "#FF00FF",
        "text_info": "#00FFFF",
        "text_error": "#FF3131",
        "font": ("Consolas", 20),
        "button_bg": "#2e003e",
        "button_fg": "#FF00FF",
        "button_hover_bg": "#660099",
        "button_active_bg": "#9900cc",
        "entry_font": ("Consolas", 28),
    },
    "desert": {
        "background": "#3e2f1c",
        "text_default": "#FFD700",
        "text_user_cmd": "#FF8C00",
        "text_info": "#F5DEB3",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#704214",
        "button_fg": "#FFD700",
        "button_hover_bg": "#a0522d",
        "button_active_bg": "#d2691e",
        "entry_font": ("Consolas", 28),
    },
    "midnight_blue": {
        "background": "#001f3f",
        "text_default": "#7FDBFF",
        "text_user_cmd": "#39CCCC",
        "text_info": "#00BFFF",
        "text_error": "#FF4136",
        "font": ("Consolas", 20),
        "button_bg": "#003366",
        "button_fg": "#7FDBFF",
        "button_hover_bg": "#0059b3",
        "button_active_bg": "#0074D9",
        "entry_font": ("Consolas", 28),
    },
    "rose_gold": {
        "background": "#B76E79",
        "text_default": "#FFF0F5",
        "text_user_cmd": "#C08081",
        "text_info": "#F4C2C2",
        "text_error": "#FF6F61",
        "font": ("Consolas", 20),
        "button_bg": "#A66E6E",
        "button_fg": "#FFF0F5",
        "button_hover_bg": "#C08081",
        "button_active_bg": "#D36C6C",
        "entry_font": ("Consolas", 28),
    },
    "forest": {
        "background": "#0B3D02",
        "text_default": "#9ACD32",
        "text_user_cmd": "#6B8E23",
        "text_info": "#8FBC8F",
        "text_error": "#FF0000",
        "font": ("Consolas", 20),
        "button_bg": "#2E8B57",
        "button_fg": "#9ACD32",
        "button_hover_bg": "#3CB371",
        "button_active_bg": "#228B22",
        "entry_font": ("Consolas", 28),
    },
    "ocean_mist": {
        "background": "#CCE7E8",
        "text_default": "#05445E",
        "text_user_cmd": "#189AB4",
        "text_info": "#75E6DA",
        "text_error": "#FF4C4C",
        "font": ("Consolas", 20),
        "button_bg": "#2C7873",
        "button_fg": "#05445E",
        "button_hover_bg": "#136F63",
        "button_active_bg": "#0B525B",
        "entry_font": ("Consolas", 28),
    },
    "sunflower": {
        "background": "#FFDA03",
        "text_default": "#663300",
        "text_user_cmd": "#996600",
        "text_info": "#FFB84D",
        "text_error": "#CC3300",
        "font": ("Consolas", 20),
        "button_bg": "#E6B800",
        "button_fg": "#663300",
        "button_hover_bg": "#CC9900",
        "button_active_bg": "#B37700",
        "entry_font": ("Consolas", 28),
    },
    "ice": {
        "background": "#D0F0FD",
        "text_default": "#023047",
        "text_user_cmd": "#219EBC",
        "text_info": "#8ECAE6",
        "text_error": "#FB8500",
        "font": ("Consolas", 20),
        "button_bg": "#219EBC",
        "button_fg": "#D0F0FD",
        "button_hover_bg": "#206782",
        "button_active_bg": "#023047",
        "entry_font": ("Consolas", 28),
    },
    "sandstone": {
        "background": "#C2B280",
        "text_default": "#5C4033",
        "text_user_cmd": "#A67B5B",
        "text_info": "#D2B48C",
        "text_error": "#8B4513",
        "font": ("Consolas", 20),
        "button_bg": "#A67B5B",
        "button_fg": "#5C4033",
        "button_hover_bg": "#8B6B4A",
        "button_active_bg": "#6F4E37",
        "entry_font": ("Consolas", 28),
    },
    "electric": {
        "background": "#0FF0FC",
        "text_default": "#000033",
        "text_user_cmd": "#00FFFF",
        "text_info": "#33FFFF",
        "text_error": "#FF0055",
        "font": ("Consolas", 20),
        "button_bg": "#00CED1",
        "button_fg": "#000033",
        "button_hover_bg": "#20B2AA",
        "button_active_bg": "#008B8B",
        "entry_font": ("Consolas", 28),
    },
    "carbon": {
        "background": "#1C1C1C",
        "text_default": "#E0E0E0",
        "text_user_cmd": "#A9A9A9",
        "text_info": "#B0C4DE",
        "text_error": "#FF4500",
        "font": ("Consolas", 20),
        "button_bg": "#333333",
        "button_fg": "#E0E0E0",
        "button_hover_bg": "#444444",
        "button_active_bg": "#555555",
        "entry_font": ("Consolas", 28),
    },
    "sunrise": {
        "background": "#FFCC99",
        "text_default": "#663300",
        "text_user_cmd": "#FF6600",
        "text_info": "#FF9933",
        "text_error": "#CC3300",
        "font": ("Consolas", 20),
        "button_bg": "#FF9966",
        "button_fg": "#663300",
        "button_hover_bg": "#FF6600",
        "button_active_bg": "#CC5500",
        "entry_font": ("Consolas", 28),
    },
    "violet": {
        "background": "#EE82EE",
        "text_default": "#4B0082",
        "text_user_cmd": "#8A2BE2",
        "text_info": "#DA70D6",
        "text_error": "#FF0000",
        "font": ("Consolas", 20),
        "button_bg": "#9932CC",
        "button_fg": "#4B0082",
        "button_hover_bg": "#8A2BE2",
        "button_active_bg": "#6A0DAD",
        "entry_font": ("Consolas", 28),
    },
    "cherry": {
        "background": "#330000",
        "text_default": "#FF0033",
        "text_user_cmd": "#FF3366",
        "text_info": "#FF6699",
        "text_error": "#CC0000",
        "font": ("Consolas", 20),
        "button_bg": "#660000",
        "button_fg": "#FF0033",
        "button_hover_bg": "#990000",
        "button_active_bg": "#CC0000",
        "entry_font": ("Consolas", 28),
    },
    "peacock": {
        "background": "#004d4d",
        "text_default": "#33cccc",
        "text_user_cmd": "#00b3b3",
        "text_info": "#66ffff",
        "text_error": "#ff3300",
        "font": ("Consolas", 20),
        "button_bg": "#006666",
        "button_fg": "#33cccc",
        "button_hover_bg": "#009999",
        "button_active_bg": "#00cccc",
        "entry_font": ("Consolas", 28),
    },
    "orchid": {
        "background": "#DA70D6",
        "text_default": "#4B0082",
        "text_user_cmd": "#9932CC",
        "text_info": "#BA55D3",
        "text_error": "#8B0000",
        "font": ("Consolas", 20),
        "button_bg": "#9932CC",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#7B68EE",
        "button_active_bg": "#6A5ACD",
        "entry_font": ("Consolas", 28),
    },
}

DEFAULT_PRESET = "blue"
ALL_PRESETS = list(PRESETS.keys())
current_preset = PRESETS[DEFAULT_PRESET]
